-- Seed data untuk tabel soal dan pilihan_jawaban
-- Database: softskill
-- Total: 60 soal (30 SJT, 30 EQ) dengan 4 pilihan jawaban per soal

SET NAMES utf8mb4;

INSERT INTO soal (kategori_soal_id, dimensi_id, skill, teks_soal, tipe_input, petunjuk, urutan, status) VALUES
(1, 1, 'communication', 'Dalam diskusi kelompok, kamu memiliki pendapat yang berbeda dengan mayoritas anggota. Apa yang paling mungkin kamu lakukan?', 'radio', NULL, 1, 'aktif'),
(1, 1, 'interpersonal', 'Kamu masuk ke lingkungan organisasi baru dan belum mengenal siapa pun. Apa yang biasanya kamu lakukan?', 'radio', NULL, 2, 'aktif'),
(2, 3, 'emotional', 'Ketika seseorang memberikan kritik terhadap pekerjaanmu, respons yang paling menggambarkan dirimu adalah...', 'radio', NULL, 3, 'aktif'),
(1, 4, 'interpersonal', 'Kelompokmu memiliki tugas dengan batas waktu tiga hari. Apa yang paling mungkin kamu lakukan?', 'radio', NULL, 4, 'aktif'),
(2, 2, 'communication', 'Ketika menerima instruksi yang belum sepenuhnya jelas, kamu biasanya...', 'radio', NULL, 5, 'aktif'),
(1, 3, 'interpersonal', 'Dua anggota kelompokmu sedang berselisih karena perbedaan pendapat. Apa yang akan kamu lakukan?', 'radio', NULL, 6, 'aktif'),
(2, 1, 'emotional', 'Ketika suasana hati sedang buruk, saya biasanya...', 'radio', NULL, 7, 'aktif'),
(1, 2, 'communication', 'Saat mengerjakan tugas, kamu menemukan dua cara berbeda untuk menyelesaikannya. Kamu cenderung...', 'radio', NULL, 8, 'aktif'),
(2, 1, 'interpersonal', 'Saat berada dalam kelompok yang anggotanya memiliki karakter berbeda-beda, saya...', 'radio', NULL, 9, 'aktif'),
(1, 4, 'communication', 'Temanmu meminta bantuan menyelesaikan tugas ketika kamu juga memiliki pekerjaan yang harus diselesaikan.', 'radio', NULL, 10, 'aktif'),
(2, 3, 'emotional', 'Ketika harus mengambil keputusan penting, saya lebih sering...', 'radio', NULL, 11, 'aktif'),
(1, 1, 'interpersonal', 'Dalam kegiatan organisasi, kamu diminta menjadi orang yang mempresentasikan hasil kerja kelompok.', 'radio', NULL, 12, 'aktif'),
(2, 2, 'communication', 'Ketika mempelajari sesuatu yang baru, saya lebih mudah memahami jika...', 'radio', NULL, 13, 'aktif'),
(1, 4, 'emotional', 'Jika jadwal kegiatanmu berubah secara tiba-tiba, kamu biasanya...', 'radio', NULL, 14, 'aktif'),
(2, 3, 'communication', 'Ketika menyampaikan kritik kepada teman, saya...', 'radio', NULL, 15, 'aktif'),
(1, 1, 'interpersonal', 'Saat bekerja dalam kelompok, kamu lebih menikmati...', 'radio', NULL, 16, 'aktif'),
(2, 2, 'emotional', 'Saat menghadapi masalah yang belum pernah kamu temui, kamu cenderung...', 'radio', NULL, 17, 'aktif'),
(1, 3, 'interpersonal', 'Jika teman satu kelompok melakukan kesalahan yang berdampak pada tugas bersama...', 'radio', NULL, 18, 'aktif'),
(2, 4, 'emotional', 'Saya merasa lebih nyaman ketika...', 'radio', NULL, 19, 'aktif'),
(1, 1, 'communication', 'Saat presentasi, kamu menyadari audiens mulai kehilangan perhatian.', 'radio', NULL, 20, 'aktif'),
(2, 3, 'emotional', 'Ketika mendapatkan keputusan yang tidak sesuai harapan, saya...', 'radio', NULL, 21, 'aktif'),
(1, 2, 'interpersonal', 'Dalam menyusun kegiatan organisasi, kamu lebih tertarik...', 'radio', NULL, 22, 'aktif'),
(2, 1, 'communication', 'Ketika berbicara dengan orang yang baru dikenal, saya...', 'radio', NULL, 23, 'aktif'),
(1, 4, 'interpersonal', 'Kamu mendapat tugas tambahan yang harus selesai hari ini.', 'radio', NULL, 24, 'aktif'),
(2, 3, 'communication', 'Dalam diskusi, saya lebih memperhatikan...', 'radio', NULL, 25, 'aktif'),
(1, 1, 'interpersonal', 'Ketika temanmu terlihat mengalami masalah tetapi tidak bercerita...', 'radio', NULL, 26, 'aktif'),
(2, 2, 'communication', 'Ketika menjelaskan ide yang rumit, saya biasanya...', 'radio', NULL, 27, 'aktif'),
(1, 4, 'emotional', 'Kamu mempunyai agenda yang sudah direncanakan, tetapi teman mengajak melakukan kegiatan spontan.', 'radio', NULL, 28, 'aktif'),
(2, 1, 'interpersonal', 'Dalam kelompok, saya merasa paling nyaman ketika...', 'radio', NULL, 29, 'aktif'),
(1, 3, 'communication', 'Jika dua pilihan memiliki kelebihan dan kekurangan yang hampir sama...', 'radio', NULL, 30, 'aktif'),
(2, 1, 'emotional', 'Saya dapat menyadari ketika emosi saya mulai memengaruhi cara saya berbicara.', 'radio', NULL, 31, 'aktif'),
(1, 2, 'interpersonal', 'Kelompokmu ingin membuat sebuah program baru. Kamu akan...', 'radio', NULL, 32, 'aktif'),
(2, 4, 'communication', 'Saya lebih mudah bekerja jika target pekerjaan sudah jelas sejak awal.', 'radio', NULL, 33, 'aktif'),
(1, 3, 'emotional', 'Seorang teman tidak setuju dengan keputusanmu dan menyampaikannya secara langsung.', 'radio', NULL, 34, 'aktif'),
(2, 1, 'communication', 'Saya tidak keberatan menyampaikan pendapat di depan banyak orang.', 'radio', NULL, 35, 'aktif'),
(1, 4, 'interpersonal', 'Dalam sebuah proyek, anggota kelompok belum menyelesaikan bagiannya menjelang deadline.', 'radio', NULL, 36, 'aktif'),
(2, 2, 'emotional', 'Saya sering membayangkan berbagai kemungkinan yang dapat terjadi sebelum mengambil keputusan.', 'radio', NULL, 37, 'aktif'),
(1, 1, 'interpersonal', 'Kamu berada dalam kelompok yang anggotanya lebih dominan berbicara daripada kamu.', 'radio', NULL, 38, 'aktif'),
(2, 3, 'communication', 'Dalam menyelesaikan konflik, saya berusaha memisahkan masalah dari pribadi orang yang terlibat.', 'radio', NULL, 39, 'aktif'),
(1, 4, 'emotional', 'Jika tugas yang kamu rencanakan selesai hari ini ternyata belum selesai...', 'radio', NULL, 40, 'aktif'),
(2, 1, 'interpersonal', 'Saya dapat menyesuaikan gaya komunikasi ketika berbicara dengan orang yang berbeda.', 'radio', NULL, 41, 'aktif'),
(1, 2, 'communication', 'Ketika diberi masalah yang belum memiliki solusi jelas, kamu...', 'radio', NULL, 42, 'aktif'),
(2, 3, 'emotional', 'Saya tetap dapat membuat keputusan ketika sedang berada dalam tekanan.', 'radio', NULL, 43, 'aktif'),
(1, 1, 'communication', 'Saat menyampaikan informasi penting, kamu ingin memastikan orang lain benar-benar memahami maksudmu.', 'radio', NULL, 44, 'aktif'),
(2, 4, 'interpersonal', 'Saya merasa lebih tenang ketika pekerjaan sudah diselesaikan jauh sebelum deadline.', 'radio', NULL, 45, 'aktif'),
(1, 3, 'interpersonal', 'Ketika kelompok harus memilih satu dari dua solusi, kamu...', 'radio', NULL, 46, 'aktif'),
(2, 2, 'communication', 'Saya tertarik memikirkan bagaimana sebuah masalah dapat diselesaikan dengan cara yang berbeda dari biasanya.', 'radio', NULL, 47, 'aktif'),
(1, 1, 'emotional', 'Kamu merasa kesal karena seseorang salah memahami ucapanmu.', 'radio', NULL, 48, 'aktif'),
(2, 4, 'communication', 'Saya cenderung membuat daftar atau catatan agar pekerjaan saya lebih teratur.', 'radio', NULL, 49, 'aktif'),
(1, 3, 'emotional', 'Temanmu gagal dalam sebuah seleksi dan terlihat kecewa.', 'radio', NULL, 50, 'aktif'),
(2, 1, 'interpersonal', 'Saya merasa energi saya bertambah ketika berada bersama banyak orang.', 'radio', NULL, 51, 'aktif'),
(1, 2, 'communication', 'Dalam memahami suatu konsep baru, kamu lebih sering...', 'radio', NULL, 52, 'aktif'),
(2, 3, 'interpersonal', 'Saat terjadi perbedaan pendapat, saya dapat tetap menghargai orang yang memiliki pendapat berbeda.', 'radio', NULL, 53, 'aktif'),
(1, 4, 'emotional', 'Tiba-tiba dosen mengubah deadline tugas menjadi lebih cepat.', 'radio', NULL, 54, 'aktif'),
(2, 1, 'communication', 'Saya nyaman meminta klarifikasi ketika tidak memahami maksud seseorang.', 'radio', NULL, 55, 'aktif'),
(1, 3, 'interpersonal', 'Dalam sebuah keputusan kelompok, kamu mengetahui bahwa pilihan mayoritas memiliki risiko tertentu.', 'radio', NULL, 56, 'aktif'),
(2, 2, 'emotional', 'Saya sering melihat hubungan antara beberapa hal yang sebelumnya terlihat tidak berkaitan.', 'radio', NULL, 57, 'aktif'),
(1, 4, 'communication', 'Kamu mendapat tugas tetapi instruksi dan deadline belum dijelaskan secara lengkap.', 'radio', NULL, 58, 'aktif'),
(2, 1, 'emotional', 'Ketika menghadapi situasi yang membuat saya marah, saya mampu menahan diri agar tidak langsung bereaksi.', 'radio', NULL, 59, 'aktif'),
(1, 1, 'interpersonal', 'Dalam kerja kelompok, kamu melihat ada anggota yang merasa tidak dilibatkan.', 'radio', NULL, 60, 'aktif');

INSERT INTO pilihan_jawaban (soal_id, teks_pilihan, bobot, indikator, urutan) VALUES
(1, 'Menyampaikan pendapat dengan jelas dan membuka ruang diskusi.', 5, 'positif', 1),
(1, 'Menunggu sampai ada anggota lain yang menyampaikan pendapat serupa.', 3, 'netral', 2),
(1, 'Mengikuti keputusan kelompok agar diskusi cepat selesai.', 2, 'negatif', 3),
(1, 'Tidak menyampaikan pendapat karena takut menimbulkan perdebatan.', 1, 'negatif', 4),
(2, 'Mencoba menyapa dan membuka percakapan dengan anggota lain.', 5, 'positif', 1),
(2, 'Menunggu ada orang yang mengajak berbicara terlebih dahulu.', 3, 'netral', 2),
(2, 'Mengamati situasi cukup lama sebelum berinteraksi.', 2, 'negatif', 3),
(2, 'Memilih tetap sendiri selama memungkinkan.', 1, 'negatif', 4),
(3, 'Saya langsung memahami bahwa kritik tersebut merupakan masukan yang perlu dipertimbangkan.', 5, 'positif', 1),
(3, 'Saya merasa kurang nyaman tetapi tetap mencoba mendengarkannya.', 4, 'positif', 2),
(3, 'Saya cenderung memikirkan alasan orang tersebut mengkritik saya.', 3, 'netral', 3),
(3, 'Saya merasa tersinggung dan sulit menerima kritik.', 2, 'negatif', 4),
(4, 'Membuat pembagian tugas dan jadwal penyelesaian sejak awal.', 5, 'positif', 1),
(4, 'Menentukan tugas utama terlebih dahulu lalu menyesuaikan sisanya.', 4, 'positif', 2),
(4, 'Mengerjakan bagian sendiri dan melihat perkembangan kelompok.', 3, 'netral', 3),
(4, 'Menunggu sampai mendekati batas waktu sebelum menentukan langkah.', 1, 'negatif', 4),
(5, 'Meminta contoh konkret agar saya memahami maksud instruksi.', 5, 'positif', 1),
(5, 'Mencoba memahami konteks dan tujuan dari instruksi tersebut.', 4, 'positif', 2),
(5, 'Mengerjakan berdasarkan pemahaman saya terlebih dahulu.', 3, 'netral', 3),
(5, 'Menunggu orang lain menjelaskan lebih lanjut.', 2, 'negatif', 4),
(6, 'Mendengarkan kedua pihak dan membantu mencari solusi yang dapat diterima bersama.', 5, 'positif', 1),
(6, 'Mencari fakta masalah sebelum menentukan langkah.', 4, 'positif', 2),
(6, 'Membiarkan mereka menyelesaikan masalah sendiri.', 3, 'netral', 3),
(6, 'Mendukung pihak yang menurut saya lebih dekat dengan saya.', 2, 'negatif', 4),
(7, 'Menyadari penyebabnya dan mengatur diri sebelum berinteraksi dengan orang lain.', 5, 'positif', 1),
(7, 'Mencoba melakukan kegiatan yang membuat suasana hati membaik.', 4, 'positif', 2),
(7, 'Tetap beraktivitas meskipun emosi sedang kurang baik.', 3, 'netral', 3),
(7, 'Mudah menunjukkan suasana hati kepada orang di sekitar.', 2, 'negatif', 4),
(8, 'Membandingkan kedua cara berdasarkan fakta dan kemungkinan hasilnya.', 5, 'positif', 1),
(8, 'Memilih cara yang pernah berhasil digunakan sebelumnya.', 4, 'positif', 2),
(8, 'Mencoba salah satu cara dan melihat hasilnya.', 3, 'netral', 3),
(8, 'Memilih cara yang terasa paling menarik.', 2, 'negatif', 4),
(9, 'Berusaha memahami karakter setiap anggota dan menyesuaikan cara berkomunikasi.', 5, 'positif', 1),
(9, 'Mencoba bersikap ramah kepada semua anggota.', 4, 'positif', 2),
(9, 'Lebih nyaman berinteraksi dengan orang yang memiliki karakter mirip.', 3, 'netral', 3),
(9, 'Tidak terlalu memikirkan perbedaan karakter.', 2, 'negatif', 4),
(10, 'Menjelaskan kondisi saya dan menentukan waktu yang realistis untuk membantu.', 5, 'positif', 1),
(10, 'Mencoba membantu sebisa mungkin setelah menyelesaikan bagian utama pekerjaan.', 4, 'positif', 2),
(10, 'Langsung membantu meskipun pekerjaan saya mungkin terlambat.', 3, 'netral', 3),
(10, 'Menolak tanpa menjelaskan alasannya.', 2, 'negatif', 4),
(11, 'Mempertimbangkan dampak keputusan terhadap orang lain sekaligus kondisi yang ada.', 5, 'positif', 1),
(11, 'Menggabungkan pertimbangan logis dan perasaan.', 4, 'positif', 2),
(11, 'Lebih mengutamakan data dan hasil.', 3, 'netral', 3),
(11, 'Mengikuti keputusan yang menurut saya paling masuk akal tanpa banyak mempertimbangkan perasaan orang lain.', 2, 'negatif', 4),
(12, 'Saya bersedia mengambil peran tersebut dan mempersiapkan penyampaian materi.', 5, 'positif', 1),
(12, 'Saya bersedia jika tidak ada anggota lain yang ingin melakukannya.', 4, 'positif', 2),
(12, 'Saya lebih memilih membantu dari belakang layar.', 2, 'negatif', 3),
(12, 'Saya akan menghindari peran tersebut.', 1, 'negatif', 4),
(13, 'Ada contoh nyata yang menunjukkan penerapannya.', 5, 'positif', 1),
(13, 'Ada penjelasan konsep sekaligus contoh.', 4, 'positif', 2),
(13, 'Saya dapat mencoba sendiri.', 3, 'netral', 3),
(13, 'Saya cukup membaca gambaran umumnya.', 2, 'negatif', 4),
(14, 'Menyesuaikan rencana dengan cepat dan menentukan prioritas baru.', 5, 'positif', 1),
(14, 'Mencari alternatif yang paling memungkinkan.', 4, 'positif', 2),
(14, 'Membutuhkan waktu untuk menyesuaikan diri.', 3, 'netral', 3),
(14, 'Merasa terganggu karena rencana berubah.', 2, 'negatif', 4),
(15, 'Menyampaikan secara jelas tetapi tetap mempertimbangkan perasaannya.', 5, 'positif', 1),
(15, 'Menyampaikan fakta masalah dan memberikan saran.', 4, 'positif', 2),
(15, 'Memilih kata-kata yang sangat halus agar tidak menyinggung.', 3, 'netral', 3),
(15, 'Cenderung menghindari memberikan kritik secara langsung.', 2, 'negatif', 4),
(16, 'Berdiskusi dan bertukar ide dengan anggota lain.', 5, 'positif', 1),
(16, 'Bekerja bersama tetapi tetap memiliki bagian sendiri.', 4, 'positif', 2),
(16, 'Mengerjakan bagian tertentu secara mandiri.', 3, 'netral', 3),
(16, 'Bekerja sendiri tanpa banyak interaksi.', 1, 'negatif', 4),
(17, 'Mencari kemungkinan baru dan beberapa alternatif solusi.', 5, 'positif', 1),
(17, 'Mencari pengalaman atau contoh yang pernah digunakan.', 4, 'positif', 2),
(17, 'Mencoba solusi yang menurut saya paling sederhana.', 3, 'netral', 3),
(17, 'Menunggu arahan dari orang lain.', 2, 'negatif', 4),
(18, 'Membicarakannya secara terbuka dan mencari cara memperbaiki masalah.', 5, 'positif', 1),
(18, 'Menjelaskan kesalahan berdasarkan fakta tanpa menyalahkan pribadi.', 4, 'positif', 2),
(18, 'Memperbaiki sendiri agar tugas selesai.', 3, 'netral', 3),
(18, 'Menegur dengan keras agar tidak mengulanginya.', 2, 'negatif', 4),
(19, 'Saya mengetahui apa yang harus dilakukan dan kapan harus menyelesaikannya.', 5, 'positif', 1),
(19, 'Ada rencana tetapi masih tersedia ruang untuk perubahan.', 4, 'positif', 2),
(19, 'Saya dapat menyesuaikan kegiatan sesuai keadaan.', 3, 'netral', 3),
(19, 'Saya tidak perlu terlalu terikat dengan jadwal.', 2, 'negatif', 4),
(20, 'Mengubah cara penyampaian dengan memberikan contoh atau pertanyaan.', 5, 'positif', 1),
(20, 'Mempercepat bagian yang kurang penting.', 4, 'positif', 2),
(20, 'Tetap mengikuti materi sesuai rencana.', 3, 'netral', 3),
(20, 'Mengakhiri presentasi secepat mungkin.', 2, 'negatif', 4),
(21, 'Menerima hasilnya lalu mengevaluasi apa yang bisa diperbaiki.', 5, 'positif', 1),
(21, 'Mencari alasan mengapa keputusan tersebut terjadi.', 4, 'positif', 2),
(21, 'Merasa kecewa tetapi tetap melanjutkan kegiatan.', 3, 'netral', 3),
(21, 'Sulit berhenti memikirkan kekecewaan tersebut.', 2, 'negatif', 4),
(22, 'Mengembangkan konsep baru yang belum pernah dicoba.', 5, 'positif', 1),
(22, 'Mengembangkan kegiatan lama dengan beberapa perubahan.', 4, 'positif', 2),
(22, 'Menggunakan format kegiatan yang sudah terbukti.', 3, 'netral', 3),
(22, 'Mengikuti format yang telah ditentukan.', 2, 'negatif', 4),
(23, 'Mudah membuka percakapan dan mencari topik yang nyaman.', 5, 'positif', 1),
(23, 'Dapat berbicara jika topiknya sudah jelas.', 4, 'positif', 2),
(23, 'Lebih banyak mendengarkan.', 3, 'netral', 3),
(23, 'Biasanya merasa canggung untuk memulai pembicaraan.', 2, 'negatif', 4),
(24, 'Mengatur ulang prioritas dan segera menyelesaikan tugas yang paling penting.', 5, 'positif', 1),
(24, 'Menyusun urutan pengerjaan berdasarkan tingkat urgensi.', 4, 'positif', 2),
(24, 'Mengerjakan sesuai urutan tugas yang sudah ada.', 3, 'netral', 3),
(24, 'Merasa kesulitan karena rencana awal berubah.', 2, 'negatif', 4),
(25, 'Apakah argumen yang disampaikan memiliki alasan dan bukti yang kuat.', 5, 'positif', 1),
(25, 'Apakah argumen tersebut masuk akal dan tetap mempertimbangkan kondisi orang lain.', 4, 'positif', 2),
(25, 'Bagaimana pendapat tersebut dapat diterima anggota lain.', 3, 'netral', 3),
(25, 'Apakah semua orang merasa nyaman dengan keputusan.', 2, 'negatif', 4),
(26, 'Saya mencoba mendekati dan menawarkan bantuan tanpa memaksanya bercerita.', 5, 'positif', 1),
(26, 'Saya memberi kesempatan sampai dia siap bercerita.', 4, 'positif', 2),
(26, 'Saya menunggu sampai dia meminta bantuan.', 3, 'netral', 3),
(26, 'Saya tidak ikut campur karena itu masalah pribadi.', 2, 'negatif', 4),
(27, 'Menggunakan analogi, contoh, dan gambaran agar lebih mudah dipahami.', 5, 'positif', 1),
(27, 'Menjelaskan konsep utama lalu memberikan contoh.', 4, 'positif', 2),
(27, 'Menjelaskan sesuai urutan yang saya pahami.', 3, 'netral', 3),
(27, 'Langsung menyampaikan inti tanpa banyak penjelasan.', 2, 'negatif', 4),
(28, 'Mempertimbangkan agenda dan mencari waktu lain yang tetap memungkinkan.', 5, 'positif', 1),
(28, 'Menyesuaikan jika agenda utama masih dapat dilakukan.', 4, 'positif', 2),
(28, 'Mengikuti kegiatan spontan jika terlihat menarik.', 3, 'netral', 3),
(28, 'Membatalkan agenda awal tanpa banyak pertimbangan.', 2, 'negatif', 4),
(29, 'Bisa berdiskusi, bertukar pendapat, dan berkontribusi secara aktif.', 5, 'positif', 1),
(29, 'Ada komunikasi yang cukup tetapi tetap ada waktu bekerja sendiri.', 4, 'positif', 2),
(29, 'Tugas saya jelas dan tidak terlalu banyak diskusi.', 3, 'netral', 3),
(29, 'Saya dapat menyelesaikan tugas secara mandiri.', 2, 'negatif', 4),
(30, 'Membandingkan konsekuensi masing-masing sebelum menentukan pilihan.', 5, 'positif', 1),
(30, 'Memilih berdasarkan kebutuhan utama saat itu.', 4, 'positif', 2),
(30, 'Mengikuti pilihan yang paling disukai anggota kelompok.', 3, 'netral', 3),
(30, 'Memilih berdasarkan intuisi pribadi.', 2, 'negatif', 4),
(31, 'Sangat sesuai', 5, 'positif', 1),
(31, 'Sesuai', 4, 'positif', 2),
(31, 'Kadang-kadang', 3, 'netral', 3),
(31, 'Tidak sesuai', 2, 'negatif', 4),
(32, 'Mengusulkan beberapa konsep dan membandingkan kemungkinan pengembangannya.', 5, 'positif', 1),
(32, 'Mencari contoh program sejenis sebagai referensi.', 4, 'positif', 2),
(32, 'Memilih konsep yang sudah terbukti berhasil.', 3, 'netral', 3),
(32, 'Mengikuti konsep yang dipilih ketua.', 2, 'negatif', 4),
(33, 'Sangat sesuai', 5, 'positif', 1),
(33, 'Sesuai', 4, 'positif', 2),
(33, 'Cukup sesuai', 3, 'netral', 3),
(33, 'Tidak terlalu sesuai', 2, 'negatif', 4),
(34, 'Saya mendengarkan alasannya dan menilai apakah ada hal yang perlu saya pertimbangkan.', 5, 'positif', 1),
(34, 'Saya menjelaskan alasan keputusan saya dengan tenang.', 4, 'positif', 2),
(34, 'Saya mencoba menghindari perdebatan.', 3, 'netral', 3),
(34, 'Saya merasa pendapat saya tidak dihargai.', 2, 'negatif', 4),
(35, 'Sangat sesuai', 5, 'positif', 1),
(35, 'Sesuai', 4, 'positif', 2),
(35, 'Kadang-kadang', 3, 'netral', 3),
(35, 'Tidak sesuai', 2, 'negatif', 4),
(36, 'Menghubungi anggota tersebut dan membantu menentukan langkah agar tugas selesai.', 5, 'positif', 1),
(36, 'Mengingatkan deadline dan meminta kepastian penyelesaian.', 4, 'positif', 2),
(36, 'Menunggu sampai waktunya mendekati deadline.', 3, 'netral', 3),
(36, 'Langsung mengambil alih tugasnya.', 2, 'negatif', 4),
(37, 'Sangat sesuai', 5, 'positif', 1),
(37, 'Sesuai', 4, 'positif', 2),
(37, 'Kadang-kadang', 3, 'netral', 3),
(37, 'Tidak sesuai', 2, 'negatif', 4),
(38, 'Tetap mencari kesempatan untuk menyampaikan ide ketika waktunya tepat.', 5, 'positif', 1),
(38, 'Menyampaikan pendapat jika diminta.', 4, 'positif', 2),
(38, 'Lebih memilih mendengarkan.', 3, 'netral', 3),
(38, 'Membiarkan anggota lain mengambil semua keputusan.', 2, 'negatif', 4),
(39, 'Sangat sesuai', 5, 'positif', 1),
(39, 'Sesuai', 4, 'positif', 2),
(39, 'Kadang-kadang', 3, 'netral', 3),
(39, 'Tidak sesuai', 2, 'negatif', 4),
(40, 'Mengevaluasi bagian yang belum selesai dan membuat rencana baru.', 5, 'positif', 1),
(40, 'Melanjutkan sampai selesai meskipun waktunya berubah.', 4, 'positif', 2),
(40, 'Menundanya sampai besok jika tidak terlalu mendesak.', 3, 'netral', 3),
(40, 'Merasa terganggu karena target tidak tercapai.', 2, 'negatif', 4),
(41, 'Sangat sesuai', 5, 'positif', 1),
(41, 'Sesuai', 4, 'positif', 2),
(41, 'Kadang-kadang', 3, 'netral', 3),
(41, 'Tidak sesuai', 2, 'negatif', 4),
(42, 'Mencoba melihat masalah dari beberapa sudut pandang.', 5, 'positif', 1),
(42, 'Mencari referensi atau pengalaman sebelumnya.', 4, 'positif', 2),
(42, 'Memilih solusi yang paling umum digunakan.', 3, 'netral', 3),
(42, 'Menunggu petunjuk lebih lanjut.', 2, 'negatif', 4),
(43, 'Sangat sesuai', 5, 'positif', 1),
(43, 'Sesuai', 4, 'positif', 2),
(43, 'Kadang-kadang', 3, 'netral', 3),
(43, 'Tidak sesuai', 2, 'negatif', 4),
(44, 'Menjelaskan dengan cara berbeda dan memastikan kembali pemahamannya.', 5, 'positif', 1),
(44, 'Memberikan contoh agar lebih mudah dipahami.', 4, 'positif', 2),
(44, 'Mengulangi informasi yang sama.', 3, 'netral', 3),
(44, 'Menganggap orang lain akan memahami sendiri.', 2, 'negatif', 4),
(45, 'Sangat sesuai', 5, 'positif', 1),
(45, 'Sesuai', 4, 'positif', 2),
(45, 'Kadang-kadang', 3, 'netral', 3),
(45, 'Tidak sesuai', 2, 'negatif', 4),
(46, 'Membandingkan keuntungan, risiko, dan dampaknya terhadap kelompok.', 5, 'positif', 1),
(46, 'Mendengarkan alasan setiap anggota kemudian mempertimbangkannya.', 4, 'positif', 2),
(46, 'Memilih solusi yang paling disukai mayoritas.', 3, 'netral', 3),
(46, 'Memilih berdasarkan perasaan terhadap pilihan tersebut.', 2, 'negatif', 4),
(47, 'Sangat sesuai', 5, 'positif', 1),
(47, 'Sesuai', 4, 'positif', 2),
(47, 'Kadang-kadang', 3, 'netral', 3),
(47, 'Tidak sesuai', 2, 'negatif', 4),
(48, 'Menjelaskan kembali maksud saya dengan tenang.', 5, 'positif', 1),
(48, 'Mencoba mencari bagian mana yang menyebabkan salah paham.', 4, 'positif', 2),
(48, 'Membiarkannya selama masalah tidak besar.', 3, 'netral', 3),
(48, 'Menunjukkan bahwa saya merasa kesal.', 2, 'negatif', 4),
(49, 'Sangat sesuai', 5, 'positif', 1),
(49, 'Sesuai', 4, 'positif', 2),
(49, 'Kadang-kadang', 3, 'netral', 3),
(49, 'Tidak sesuai', 2, 'negatif', 4),
(50, 'Mendengarkan ceritanya dan membantu melihat apa yang dapat dipelajari.', 5, 'positif', 1),
(50, 'Memberikan dukungan dan membantunya mempersiapkan kesempatan berikutnya.', 4, 'positif', 2),
(50, 'Memberikan saran agar dia mencoba lagi.', 3, 'netral', 3),
(50, 'Mengatakan bahwa kegagalan adalah hal biasa.', 2, 'negatif', 4),
(51, 'Sangat sesuai', 5, 'positif', 1),
(51, 'Sesuai', 4, 'positif', 2),
(51, 'Kadang-kadang', 3, 'netral', 3),
(51, 'Tidak sesuai', 2, 'negatif', 4),
(52, 'Menghubungkan konsep tersebut dengan ide atau kemungkinan lain.', 5, 'positif', 1),
(52, 'Mencari contoh nyata penerapannya.', 4, 'positif', 2),
(52, 'Mengikuti penjelasan langkah demi langkah.', 3, 'netral', 3),
(52, 'Menghafalkan informasi utama.', 2, 'negatif', 4),
(53, 'Sangat sesuai', 5, 'positif', 1),
(53, 'Sesuai', 4, 'positif', 2),
(53, 'Kadang-kadang', 3, 'netral', 3),
(53, 'Tidak sesuai', 2, 'negatif', 4),
(54, 'Segera menyusun ulang prioritas dan menyesuaikan jadwal.', 5, 'positif', 1),
(54, 'Mengerjakan bagian paling penting terlebih dahulu.', 4, 'positif', 2),
(54, 'Berusaha mengikuti perubahan sambil tetap menggunakan rencana lama.', 3, 'netral', 3),
(54, 'Merasa sangat terganggu karena perubahan mendadak.', 2, 'negatif', 4),
(55, 'Sangat sesuai', 5, 'positif', 1),
(55, 'Sesuai', 4, 'positif', 2),
(55, 'Kadang-kadang', 3, 'netral', 3),
(55, 'Tidak sesuai', 2, 'negatif', 4),
(56, 'Menyampaikan risiko tersebut dan memberikan alternatif solusi.', 5, 'positif', 1),
(56, 'Menjelaskan risiko berdasarkan fakta yang ada.', 4, 'positif', 2),
(56, 'Mengikuti keputusan mayoritas jika risikonya masih dapat diterima.', 3, 'netral', 3),
(56, 'Tidak menyampaikan karena khawatir menghambat keputusan.', 2, 'negatif', 4),
(57, 'Sangat sesuai', 5, 'positif', 1),
(57, 'Sesuai', 4, 'positif', 2),
(57, 'Kadang-kadang', 3, 'netral', 3),
(57, 'Tidak sesuai', 2, 'negatif', 4),
(58, 'Mengklarifikasi informasi yang kurang sebelum mulai mengerjakan.', 5, 'positif', 1),
(58, 'Mulai mengerjakan bagian yang sudah jelas sambil mencari informasi tambahan.', 4, 'positif', 2),
(58, 'Menunggu instruksi lengkap.', 3, 'netral', 3),
(58, 'Mengerjakan sesuai perkiraan sendiri.', 2, 'negatif', 4),
(59, 'Sangat sesuai', 5, 'positif', 1),
(59, 'Sesuai', 4, 'positif', 2),
(59, 'Kadang-kadang', 3, 'netral', 3),
(59, 'Tidak sesuai', 2, 'negatif', 4),
(60, 'Mengajak anggota tersebut menyampaikan pendapat dan memastikan ia mendapat peran.', 5, 'positif', 1),
(60, 'Menanyakan apakah ia membutuhkan bantuan.', 4, 'positif', 2),
(60, 'Membiarkannya memilih sendiri apakah ingin terlibat.', 3, 'netral', 3),
(60, 'Menganggap ia memang tidak tertarik terlibat.', 2, 'negatif', 4);
